apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.stable.goci.io
spec:
  group: stable.goci.io
  scope: Namespaced
  names:
    plural: applications
    singular: application
    kind: Application
    shortNames:
    - app
    - apps
    categories:
    - all
    - goci
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            properties:
              topics:
                type: array
                maxItems: 6
                items:
                  type: string
                  maxLength: 21
              description:
                type: string
                maxLength: 128
              primaryResponsibleTeam:
                type: string
                maxLength: 56
                description: 'Name of a Team primarily responsible for this Application'

              providers:
                type: object
                properties:
                  github:
                    type: object
                    description: 'Configure GitHub Webhooks and Actions for your Application Repository'
                    required:
                    - baseUrl
                    - repository
                    - organization
                    properties:
                      baseUrl:
                        type: string
                        default: github.com
                      organization:
                        type: string
                        maxLength: 56
                      installationId:
                        type: string
                        maxLength: 128
                        description: 'ID of installed goci.io/bot Github App'
                      repository:
                        type: object
                        required:
                        - name
                        - create
                        properties:
                          name:
                            type: string
                          create:
                            type: boolean
                            default: true
                            description: 'Creates a new Repository for this Application'
                      webhooks:
                        type: array
                        description: 'Github Webhooks for this Application Repository'
                        items:
                          type: object
                          required:
                          - events
                          - url
                          properties:
                            events:
                              type: array
                              minItems: 1
                              maxItems: 10
                              items:
                                type: string
                            url:
                              type: string

                  atlantis:
                    type: object
                    description: 'Adds atlantis Repo-Level config, enables Atlantis Webhooks and Status Checks'
                    required:
                    - domain
                    - projects
                    - workspaces
                    properties:
                      domain:
                        type: string
                      workspaces:
                        type: array
                        minItems: 1
                        maxItems: 10
                        default:
                        - name: default
                          workflow: default
                        items:
                          type: object
                          required:
                          - name
                          - workflow
                          properties:
                            name:
                              type: string
                            workflow:
                              type: string
                              default: default
                            autoplan:
                              type: boolean
                              default: true
                      projects:
                        type: array
                        minItems: 1
                        maxItems: 10
                        items:
                          type: object
                          required:
                          - name
                          - directory
                          properties:
                            name:
                              type: string
                            directory:
                              type: string
                              default: '.'
                            terraformVersion:
                              type: string
                              default: 0.12.26

          status:
            type: object
            required:
            - ready
            - phase
            properties:
              ready:
                type: boolean
                default: false
              phase:
                type: string
                default: Pending
                enum:
                - Pending
                - Provisioning
                - Destroying
                - Modifying
                - Error
                - Ready
              stackVersion:
                type: string
                description: 'Current Version used to provision or update the Application'
              job:
                type: string
                description: 'ID of an Job fulfilling tasks to change into desired Ready state'
              error:
                type: object
                required:
                - code
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  provider:
                    type: string
                    description: 'Provider which issued the Error'
    additionalPrinterColumns:
    - name: Phase
      type: string
      description: Current phase the Application is in
      jsonPath: .status.phase
    - name: Team
      type: string
      description: Team or Group primarily responsible
      jsonPath: .spec.primaryResponsibleTeam
