apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: environments.stable.goci.io
spec:
  group: stable.goci.io
  scope: Namespaced
  names:
    plural: environments
    singular: environment
    kind: Environment
    shortNames:
    - env
    - envs
    categories:
    - all
    - goci
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - type
            properties:
              description:
                type: string
              type:
                type: string
                enum:
                - ci
                - staging
                - production
          status:
            type: object
            required:
            - ready
            - phase
            properties:
              ready:
                type: boolean
                default: false
              phase:
                type: string
                default: Pending
                enum:
                - Pending
                - Provisioning
                - Destroying
                - Modifying
                - Error
                - Ready
              stackVersion:
                type: string
                description: 'Current Version used to provision or update the Environment'
              job:
                type: string
                description: 'ID of an Job fulfilling tasks to change into desired Ready state'
              error:
                type: object
                required:
                - code
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  provider:
                    type: string
                    description: 'Provider which issued the Error'
    additionalPrinterColumns:
    - name: Type
      type: string
      description: Type of the environment
      jsonPath: .spec.type
    - name: Phase
      type: string
      description: Current phase the environment is in
      jsonPath: .status.phase
