apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tools.stable.goci.io
spec:
  group: stable.goci.io
  scope: Namespaced
  names:
    plural: tools
    singular: tool
    kind: Tool
    categories:
    - all
    - goci
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - input
            - module
            properties:
              module:
                type: object
                properties:
                  terraform:
                    type: object
                    properties:
                      version:
                        type: string
                      source:
                        type: string
                      sourceVersion:
                        type: string
                  docker:
                    type: object
                    properties:
                      image:
                        type: string
                        maxLength: 96
                      version:
                        type: string
                        maxLength: 60
                oneOf:
                - required:
                  - terraform
                  properties:
                    terraform:
                      required:
                      - version
                      - source
                      - sourceVersion
                - required:
                  - docker
                  properties:
                    docker:
                      required:
                      - image
                      - version

              providers:
                type: object
                properties:
                  github:
                    type: object
                    properties:
                      gociBotEnabled:
                        type: boolean
                        default: false
                      organization:
                        type: string
                        description: 'GitHub Organization when using goci.io/bot App'
                      installationId:
                        type: string
                        description: 'Installation ID of goci.io/bot GitHub App'
                      secretKeyRef:
                        type: object
                        description: 'Secret containing GITHUB_TOKEN and GITHUB_ORGANIZATION'
                        required:
                        - name
                        properties:
                          name:
                            type: string
                  aws:
                    type: object
                    properties:
                      secretKeyRef:
                        type: object
                        description: 'Secret containing AWS_ACCOUNT_ID, AWS_ASSUME_ROLE_NAME and AWS_STS_EXTERNAL_ID'
                        required:
                        - name
                        properties:
                          name:
                            type: string
              input:
                x-kubernetes-preserve-unknown-fields: true
              
              secretKeyRefs:
                type: array
                items:
                  type: object
                  required:
                  - name
                  properties:
                    name:
                      type: string

          status:
            type: object
            required:
            - ready
            - phase
            properties:
              ready:
                type: boolean
                default: false
              phase:
                type: string
                default: Pending
                enum:
                - Pending
                - Provisioning
                - Destroying
                - Modifying
                - Error
                - Ready
              stackVersion:
                type: string
                description: 'Current Version used to provision or update the Provider Resources'
              job:
                type: string
                description: 'ID of an Job fulfilling tasks to change into desired Ready state'
              error:
                type: object
                required:
                - code
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  provider:
                    type: string
                    description: 'Provider which issued the Error'

    additionalPrinterColumns:
    - name: Phase
      type: string
      description: Current phase the Application is in
      jsonPath: .status.phase
